# Generated by Django 5.0.4 on 2024-07-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0004_top_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.IntegerField()),
                ('pdetails', models.CharField(max_length=100, verbose_name='Product Details')),
                ('cat', models.IntegerField(choices=[(1, 'dairy'), (2, 'fruits'), (3, 'vegetables'), (4, 'Pasta_rice_cereals'), (5, 'Meat_alternatives'), (6, 'Cans_jars'), (7, 'Bread_baked'), (8, 'Frozen_food'), (9, 'sauces'), (10, 'Nuts_snacks'), (11, 'beverages'), (12, 'herbs_spices')], verbose_name='Categgory')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('is_active', models.BooleanField(default=True, verbose_name='Availabel')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Top_Product',
        ),
    ]
