# Generated by Django 5.0.4 on 2024-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0005_top_products_delete_top_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_products',
            name='cat',
            field=models.IntegerField(verbose_name='Categgory'),
        ),
    ]
