# Generated by Django 5.0.4 on 2024-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0006_alter_top_products_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_products',
            name='cat',
            field=models.IntegerField(choices=[(1, 'dairy'), (2, 'fruits'), (3, 'vegetables'), (4, 'Pasta_rice_cereals'), (5, 'Meat_alternatives'), (6, 'Cans_jars'), (7, 'Bread_baked'), (8, 'Frozen_food'), (9, 'sauces'), (10, 'Nuts_snacks'), (11, 'beverages'), (12, 'herbs_spices')], verbose_name='Categgory'),
        ),
    ]
