# Generated by Django 5.0.4 on 2024-07-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0008_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tpid',
        ),
    ]
