# Generated by Django 5.0.4 on 2024-12-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='ecomm_app.products'),
        ),
    ]
