# Generated by Django 5.0.4 on 2024-12-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0012_alter_order_pid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_Products',
        ),
    ]
